name: route_kit
description: Routing toolkit
version: 0.0.1
# homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.1.0-13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.13.1
  quiver: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0


flutter:
